### ISSUE TITLE
Replace the "Ship Your Aid" section with the new design

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#118]
CodeSee Recording:
https://app.codesee.io/shared/4bb1a720-5912-11ec-92c1-f7ca5b5ec43b

Figma design:
![Screenshot of Figma design showing the Ship your Aid](https://user-images.githubusercontent.com/656318/145443578-8dc1cafc-d947-4822-b693-3ea973c46eff.png)

Can startoff with a static image, then implement the Image Carousel to show a variety of shipment / destination related images.  Related to #32

Figma link for reference:
https://www.figma.com/file/Ey8xRnstZS4UYmqQwyYZdC/Landing-Page?node-id=208%3A600

**Comment by RabeaGleissner** [comment]
Looks like all the issues related to the milestone are either done or in progress, so I'll start working on this one.

**Comment by RabeaGleissner** [comment]
I'm going to un-assign myself from this as I haven't done much on it yet and I'm not sure if this is still a priority at the moment...

**Comment by jtfairbank** [comment]
Looks like this is done, we went with the card-style option to highlight routes.
