### ISSUE TITLE
Add Fort Pickett and In-kind donations sections to the "How we help" section in the main page

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#119]
CodeSee Recording:
https://app.codesee.io/shared/4bb1a720-5912-11ec-92c1-f7ca5b5ec43b

![Screenshot of In-kind donations Figma design](https://user-images.githubusercontent.com/656318/145444894-8850b407-5c45-4732-b602-84d3b03ab547.png)

Figma link:
https://www.figma.com/file/Ey8xRnstZS4UYmqQwyYZdC/Landing-Page?node-id=208%3A601

Text content for "In-kind Donations":

```
Distribute Aid runs a successful in-kind donation programme where we connect companies with aid organisations. Through our network of hundreds of charities we can handle coordinating large volumes of donations. To date we have secured over 5 million items through our in-kind donor programme. Email donate-aid@distributeaid.org if you can donate in-kind.
```

- [x] TODO: @jtfairbank add images and text copy for Fort Pickett section

**Comment by hola-soy-milk** [comment]
@jtfairbank Unless I'm mistaken, we need a photo for the In-kind Donations section too, correct?

**Comment by hola-soy-milk** [comment]
Hey @RabeaGleissner! Thank you once again so much for your help.

I hope you don't mind if I go ahead and handle this ahead of our launch?

**Comment by RabeaGleissner** [comment]
Don’t mind at all, please feel free @ramonh !
Apologies, I won’t have time to contribute more until mid next week or so… 
Thanks for jumping in on this one!

**Comment by hola-soy-milk** [comment]
Please don't apologise! I can't thank you for all your help so far!

I wanted to make sure I don't step on your toes :)
