### ISSUE TITLE
Change Patreon link to Donation link

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#120]
CodeSee Recording:
https://app.codesee.io/shared/4bb1a720-5912-11ec-92c1-f7ca5b5ec43b

- [ ] Make the button match that in the navigation bar

**Comment by RabeaGleissner** [comment]
Hello! Happy to have a look at this one.

**Comment by RabeaGleissner** [comment]
https://github.com/distributeaid/distributeaid.org/pull/122

**Comment by hola-soy-milk** [comment]
Thanks, @RabeaGleissner! I've assigned you

**Comment by deammer** [comment]
Resolved by #122
