### ISSUE TITLE
License or replace social network icons added in #121

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#126]
They [were added](https://github.com/distributeaid/distributeaid.org/pull/121) without acquiring permission by the original author (Figma?) first.

**Comment by hola-soy-milk** [comment]
Thanks for opening this, @coderbyheart!

To clarify, these icons were not taken from Figma itself, but from the work from our designers uploaded to Figma.

After investigating this. We've concluded that they're from in-house, and do not require licensing.

Ok to close this?

**Comment by coderbyheart** [comment]
Yes, thanks for clarifying!

**Comment by hola-soy-milk** [comment]
Thank **you**!
