### ISSUE TITLE
Improve main page carousel responsiveness

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#135]
![Screenshot showing mobile view for main page carousel](https://user-images.githubusercontent.com/656318/149378739-d3619476-7ef1-4371-8c4f-2a2bf62d81d0.png)

[CodeSee recording](https://app.codesee.io/shared/0b0b10f0-7490-11ec-a628-61bee2c3b61c)

Right now, the images are side-by-side in mobile with the title.

Would be good to have them above or below the title, with one image shown at a time, but should still rotate through them.

**Comment by RabeaGleissner** [comment]
Here's a suggestion for how to fix this: https://github.com/distributeaid/distributeaid.org/pull/153
