### ISSUE TITLE
Fix mobile responsiveness for shipment routing pages

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#136]
![Screenshot showing the layout issue in the routing pages](https://user-images.githubusercontent.com/656318/149379563-99bed487-1c2f-4787-baee-32221f07c52d.png)

Example of the issue [here](https://distributeaid.org/routes/uk-to-france).

[CodeSee recording](https://app.codesee.io/shared/0b0b10f0-7490-11ec-a628-61bee2c3b61c)

Right now, the sections are side-by-side in mobile.

Would be good to have them above or below each other.

**Comment by RabeaGleissner** [comment]
I have a bit of time today, so I can work on this! I'll also try to extract some components from these Routes pages and make them a bit more React-like.
