### ISSUE TITLE
Style the Region Template Page

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#25]
**Previous work:** add content to the regions listing (index page) and to each region page (templates).

- Index page now displays each region, along with a thumbnail of a map of the region.
- Template page now displays region information (name + full-image map) and a table of shipment data, including icons describing the category of the ship.

**Starting Point:** https://app.codesee.io/shared/eda14600-0681-11ec-bcdf-b35d3087a4b1

**Goal:**

- [x] Add cell spacing.  Alternate row background colors.

**Comment by hola-soy-milk** [comment]
Resolved in #65
