### ISSUE TITLE
Create NumbersSummary Component and Contentful Model

### ISSUE THREAD

**Issue by Panzemek** [distributeaid/distributeaid.org#31]
**Previous work:** NumbersSummary section added to Section.tsx switch statement.

- No functional code created yet for this feature.

**Starting Point:**
Recording: https://app.codesee.io/shared/99dc9ec0-3804-11ec-b5c4-e93c0b8edf5c

Map with Tour: https://app.codesee.io/maps/public/fe74c460-3805-11ec-8cad-e75806fe4532

https://www.figma.com/file/Ey8xRnstZS4UYmqQwyYZdC/Landing-Page

**Goal:**

- [ ] Add component to display a 3x2 grid of images with short captions summarizing the year's metrics.
- [ ] Add Contentful model to provide needed data for the component.

**Comment by jtfairbank** [comment]
We're going to take a different approach to gathering / displaying stats data.
