### ISSUE TITLE
Create ImageCarousel Contentful Model and Refactor to Data Object

### ISSUE THREAD

**Issue by Panzemek** [distributeaid/distributeaid.org#32]
**Previous work:** ImageCarousel section added to Section.tsx switch statement. React component created.

- The ImageCarousel displays images from an object passed into it. It is currently using a placeholder image object.

**Starting Point:**
Recording: https://app.codesee.io/shared/99dc9ec0-3804-11ec-b5c4-e93c0b8edf5c

Map with Tour: https://app.codesee.io/maps/public/fe74c460-3805-11ec-8cad-e75806fe4532

https://www.figma.com/file/Ey8xRnstZS4UYmqQwyYZdC/Landing-Page

**Goal:**

- [ ] Add Contentful model to provide needed data for the component.
- [ ] Refactor ImageCarousel to use Contentful query object structure.

**Comment by hola-soy-milk** [comment]
@jtfairbank Might we want to close these Contentful-related issues or remove the "good first issue" label for the time being?

**Comment by jtfairbank** [comment]
Taking a new approach w/ Forestry.io.  Will make another issue to get the Image Carousel onto Forestry at some point in the future.
