### ISSUE TITLE
Create MissionBanner Component and Contentful Model

### ISSUE THREAD

**Issue by Panzemek** [distributeaid/distributeaid.org#33]
**Previous work:** MissionBanner section added to Section.tsx switch statement.

- No functional code created yet for this feature.

**Starting Point:** https://app.codesee.io/data-flow/0e490f50-11b3-11ec-88f8-bb5d3013d81c

**Goal:**

- [ ] Add component to display mission statement / basic summary and chosen graphic.
- [ ] Add Contentful model to provide needed data for the component.

**Comment by hola-soy-milk** [comment]
Taylor and I can go ahead and start with this!
