### ISSUE TITLE
Add styling for Region page

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#351]
Right now, [our individual region page is largely unstyled](https://distributeaid.org/regions/greece).

This can be styled using [TailwindCSS](https://tailwindcss.com/).

Get started with our codebase's region functionality by clicking on this CodeSee Map:
[![Region Page Styling](https://user-images.githubusercontent.com/656318/174651401-c3dd1b57-7d12-4924-b41d-ed4a13bc0b99.jpeg)](https://app.codesee.io/maps/public/364bce80-f0b4-11ec-8763-7321ea8c7121)

**Comment by hola-soy-milk** [comment]
Happy to tackle this live on stream with @jtfairbank !

**Comment by noelcastillon1** [comment]
Hey! I want to work on this!

**Comment by jtfairbank** [comment]
Sounds great @noelcastillon1!  I've added you as an asignee!

**Comment by choco-develop** [comment]
hey...i will be very excited to hop-in on this task

**Comment by fedechaves** [comment]
@jtfairbank you should check this issue
