### ISSUE TITLE
Refactor: Move PageBanner Component From Content to Section

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#37]
@ramonh and @jtfairbank created the PageBanner component ( PR #35 ).  We originally thought it would be a Content component but during the implementation it made more sense as a Section component with Content components in it.  Now we need to refactor the code by moving the component to the right part of the codebase.

- [ ] Move `src/components/content/PageBanner.tsx` to `src/components/section/`.  Make sure the imports to / from the file aren't broken!
- [ ] Rename the component to `SectionPageBanner.tsx`.  Make sure to update the components name within the file!
- [ ] Please add your name to the `/Contributors.md` file if this is your first time contributing to the project!

Starting Point: https://app.codesee.io/shared/a1a61c20-278e-11ec-8a7b-bd57c9eaa54f

**Comment by pedaars** [comment]
I will take a look at this

**Comment by hola-soy-milk** [comment]
Go for it, thanks, @pedaars! 💜
