### ISSUE TITLE
Replace 3D globe visualization with 2D SVG image on devices that prefer reduced motion

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#477]
Let's use the [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) to replace this with the previously used [2D static graphic](https://github.com/distributeaid/distributeaid.org/blob/saga/src/images/homepage-banner-image.svg).

**Comment by jtfairbank** [comment]
Closed by @pavle995 in #558!
