### ISSUE TITLE
Setup "Generic" Pages & Content Components

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#523]
There are plenty of "generic" pages we need to get onto the site, such as "About Us", "How We Work", or informational pages to help our partners understand the complexities of global aid logistics.  Each of these pages has unique content, so we can't create a reusable template with custom fields.  And there are a decent number of them, so it doesn't make sense to create a specialized template for each page.

Our desired approach is to create a "generic" page template that can incorporate a standard set of content components.  This will allow DA's admin & logistics team members to create a new page in forestry and select the content blocks they need, in the order they need them.

We should take a front-to-back approach here: start by hard-coding content into a hard-coded page, and then refactor that into react templates + components, before finally setting up a forestry template and pulling the data down from forestry into our react page / components.

**CodeSee Map w/ Tour:** https://app.codesee.io/maps/public/0837df10-1efa-11ed-9245-992c0d264c17

### Page Template
Each page can have some standard fields, such as a title.  Pages will also receive an array of content sections, each of which contains it's own content blocks.

### Content Sections
Content sections can have some standard fields, such as a title, as well as an array of content blocks.  Content sections span the full width of the screen and their height is based on the amount of content they contain.  They are responsible for the layout, background color, and other section-wide styling decisions.

EX: Full width, columns, grid, etc.

### Content Blocks
Content blocks have fields based on the type of content that they are displaying.  They expand to fill the width that their wrapping section has allocated to them, and are as high as the content requires.  They are responsible for rendering the content appropriately.

EX: 

- Body text
    - Markdown field
- Image with Caption
    - Image
    - Caption Title (only sometimes applicable)
    - Caption Text
    - Attribution
- Youtube Embed
    - Youtube URL
    - Title to appear above the video
    - Possibly some parameters from these: [https://developers.google.com/youtube/player_parameters](https://developers.google.com/youtube/player_parameters).  Alternatively, Forestry could ask for the full Youtube embed link instead of just the URL, and the user would need to specify these parameters when creating the embed link.
        - cc_load_policy - 1 means captions will be shown by default
        - controls - do video player controls appear in the frame?
        - disablekb - 1 means keyboard controls are disabled
        - modestbranding - removes the Youtube logo from the bottom left)
        - loop - loops the video
        - playsinline - This parameter controls whether videos play inline or fullscreen on iOS. 0 means fullscreen.  0 is default.  1 means inline.
        - rel - If parameter is set to 0, the related videos shown at the end will only be from the same channel as the video.  If 1, could be related videos from any channel.
- General Card(s)
    - Each card
        - Image
        - Image Shape (rectangle or circle)
        - Title
        - Subtitle
        - Body Text
        - Border Color (option for transparent)
        - Body Color (option for transparent)
        - Dropdown
        - Behavior when you hover mouse over it
            - Color change?
            - Text that appears with the hover?
- Dropdown
    - Title, color of box it appears in, etc. (this is the stuff to show initially).
    - Content block(s) to appear within the dropdown when it’s clicked on.
    - For example, imagine a “What we do” page that lists three different projects, and if you click on one, the box expands with content blocks inside to explain more about that project.
- Prezi Embed (lower priority)
    - Embed link

**Comment by ghost** [comment]
Hey, can I take this?

**Comment by hola-soy-milk** [comment]
Absolutely, thank you for your help, @teachjenntech!

**Comment by hola-soy-milk** [comment]
Hey! Gonna take care of the YouTube component ✋
