### ISSUE TITLE
Create Generalized Card Template

### ISSUE THREAD

**Issue by wwwwwlwwwww** [distributeaid/distributeaid.org#547]
There is an existing card setup for region pages and a card setup being worked on for the teams page.

This functionality--having cards display information--can be applied to a lot of content areas.  

This issue involves looking at what's been done for those content-specific cards and building a more generalized card template.

Each card should include the following:

- [x] * Image
- [x] * Image Shape (rectangle or circle) #601
- [x] * Title
- [x] * Subtitle
- [x] * Body Text
- [x] * Border Color (option for transparent)
- [x] * Body Color (option for transparent)
- [ ] * ~~Behavior when you hover mouse over it - change color or have hover text appear~~

Here is a map of components that will need refactoring in order to support this issue.
https://app.codesee.io/maps/public/71737160-29f9-11ed-8f04-91f3b133c2aa

**Comment by JasonFritsche** [comment]
@wwwwwlwwwww Can we please create a separate ticket for each of the following items?

* Image Shape (rectangle or circle)
* Behavior when you hover mouse over it - change color or have hover text appear

I'll handle the remaining items in this ticket.

**Comment by coderbyheart** [comment]
Hover does not work on mobile, so I don't recommend add special functionality for that.
