### ISSUE TITLE
Codesee link not working in README

### ISSUE THREAD

**Issue by ghost** [distributeaid/distributeaid.org#550]
Hey all! 

Codesee link not working in README https://docs.codesee.io/docs/codebase-maps

![image](https://user-images.githubusercontent.com/108376073/186712992-22908ff2-612b-43d7-b9cc-1d3f85ec412c.png)
![image](https://user-images.githubusercontent.com/108376073/186713441-48a7467b-e995-482b-9cf1-84c4827ad63c.png)

**Comment by jtfairbank** [comment]
Hey thanks @teachjenntech!  It looks like CodeSee updated their link, and this is the correct one:

https://docs.codesee.io/docs/explore-your-map

Do you want to try and tackle this one?  Happy to leave it open for now as well!

---

Related to this: I noticed that the CodeSee Architecture Diagram button at the top of the readme required folks to log into CodeSee.  I believe @hola-soy-milk you created the map, or maybe @deammer?  Could y'all double check that it's shared publicly, and possibly move it so it's owned by the Distribute Aid org account on CodeSee?

**Comment by eyetech2dev** [comment]
Hello, I would love to take this one from you @teachjenntech if that is okay? This seems like a perfect issue for my very first open source PR! Thank you so much!

**Comment by jtfairbank** [comment]
That sounds great @eyetech2dev!  While you're at it, do you mind checking the other links in the readme just in case?

**Comment by eyetech2dev** [comment]
Every other link is good!
