### ISSUE TITLE
Setup Github Discussions

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#567]
Looks like Github has a [discussions](https://github.com/distributeaid/distributeaid.org/discussions/landing) message board feature where we can answer questions about the codebase and contributing to Distribute Aid. Given the increased interest in contributing to the landing site project, that sounds like a useful way to engage with new contributors in a structured manner.

This will require a maintainer to setup.  We likely want to add different categories / maybe seed some initial threads so it's immediately useful.

**Comment by hola-soy-milk** [comment]
Heavily in favour of this! I can set it up right away or get it going tomorrow on stream

**Comment by jtfairbank** [comment]
@hola-soy-milk let's do it tomorrow on the stream?  I think we'll be spending most of the time highlighting pathways for new contributors, and this might be an interesting thing to show them / we can get the audience engaged helping us pick the categories / initial topics, etc.
