### ISSUE TITLE
Get us on OpenSauced

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#573]
opensauced.pizza

**Comment by coderbyheart** [comment]
Consider moving this to a discussion, because signing up for OpenSauced does not require a code change in this repo.

**Comment by rcmtcristian** [comment]
by getting the org into opensauce do you mean being able to get added and tracked ? because that's possible [already ](https://app.opensauced.pizza/repos/distributeaid/distributeaid.org/)

**Comment by hola-soy-milk** [comment]
Oh nice! Good to know, thanks @rcmtcristian!
