### ISSUE TITLE
Netlify previews for non-member PRs fail

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#580]
This is correct, because they should not have access to our secrets.

However it would be great if there was an easy way for a maintainer to approve a build from the GitHub PR.

The "manual" way for getting a preview is to go into the Netlfy dashbord and retry a failed build there:

![image](https://user-images.githubusercontent.com/188915/188084701-245e4d8a-137d-4d4b-9966-f2310d4cd695.png)

**Comment by jtfairbank** [comment]
@coderbyheart would adding contributors to the landing site team that I've setup after they submit their first PR help with this?  The idea being that after they've contributed something real then we can be fairly trusting and by being on the team Netlify will automatically create a preview?

A quick google search didn't turn up an easy solution, but someone might have to dive into Netlify's github actions, etc.

**Comment by raae** [comment]
Are the secrets not in Netlify? Deploy previews will user them, but not expose them I thought?

**Comment by coderbyheart** [comment]
> @coderbyheart would adding contributors to the landing site team that I've setup after they submit their first PR help with this?

Yes.



> Are the secrets not in Netlify? Deploy previews will user them, but not expose them I thought?

This happens when out-of-organization contributors create a PR, then the PR is run using "their" Netlify account, which has no access to the secrets of the DistributeAid Netlify team.

**Comment by coderbyheart** [comment]
This works now.
