### ISSUE TITLE
Debug 404 error on routes pages

### ISSUE THREAD

**Issue by wwwwwlwwwww** [distributeaid/distributeaid.org#581]
Our UK to France and UK to Lebanon page on our public-facing website are currently down.  If you try to access them, you just get a 404 error.

These are the relevant pages:
https://distributeaid.org/routes/uk-to-france
https://distributeaid.org/routes/uk-to-lebanon

I don't know what the cause of the error is, but we should try to get it fixed so that the website can display correctly.

**Comment by coderbyheart** [comment]
git bisect revealed 88d85fc81ee6e2118e3f7a6aa05eb254407725fd to be the commit that causes the pages to disappear. /cc @jtfairbank

**Comment by jtfairbank** [comment]
Hey thanks @coderbyheart!  I'll look into this one on Sunday.
