### ISSUE TITLE
Create Content Block: Image with Caption

### ISSUE THREAD

**Issue by wwwwwlwwwww** [distributeaid/distributeaid.org#584]
This is one of a new set of issues being created to break down #523 into a larger number of smaller tasks to make sure that our new contributors have plenty of things they can choose to work on.  #523 has some additional context for the information below.

I'd recommend looking at #572  as an example for implementing front-end components with tests.

CodeSee Map of relevant components: https://app.codesee.io/maps/public/6b31f460-307b-11ed-9e3a-396e1494e115

### Image Fields

* image - Image
* altText - The alt text attribute for the image.
* caption - Caption Text
* attribution - Attribution of the photo.  We may or may not display this statically near the photo, have the attribution appear when you  hover over the photo, etc.
* alignmentPhoto - is the photo left, middle, or right aligned?
* alignmentCaption - is the caption title and caption left aligned, middle aligned, right aligned, or justified*?
  * If justified is at all technically difficult or time consuming to make happen, just skip it.

NOTE: We've removed the caption title attribute from photos, you can ignore it on the mockup below.

### Mockup

For the first iteration, I would just make the caption and caption title appear below the photo like so (these are two example instances of this content block):

![image](https://user-images.githubusercontent.com/112079473/188119444-36ddf05c-b59d-4649-b1f9-459acb902c02.png)

### Checklist

- [x] Sign `/CONTRIBUTORS.md` if new contributor
- [x] Add image component folder / file in `/src/components/`
- [x] Add unit tests for the component
- [x] Refactor the About Us page's Board members photo to use the new component, essentially replacing `/src/components/about-us/BoardMembers.tsx` with the new component.
- [x] Bonus points for writing an end-to-end test to ensure the about us page loads properly, and shows the board member photo properly.

**Comment by fedechaves** [comment]
Hi @jtfairbank, could I work on this issue?

**Comment by jtfairbank** [comment]
@fedechaves sure thing!

**Comment by fedechaves** [comment]
@jtfairbank you should check this issue Taylor
