### ISSUE TITLE
Create Content Block: Youtube Embed

### ISSUE THREAD

**Issue by wwwwwlwwwww** [distributeaid/distributeaid.org#585]
This is one of a new set of issues being created to break down https://github.com/distributeaid/distributeaid.org/issues/523 into a larger number of smaller tasks to make sure that our new contributors have plenty of things they can choose to work on. https://github.com/distributeaid/distributeaid.org/issues/523 has some additional context for the information below.

I'd recommend looking at #572  as an example for implementing front-end components with tests.

CodeSee Map of relevant components: https://app.codesee.io/maps/public/751203b0-3082-11ed-af0d-b58e3b81aea3

### Youtube Embed Fields

  - Youtube URL
  - Title to appear above the video (optional, will sometimes be no title)

### Checklist

- [x] Sign `/CONTRIBUTORS.md` if new contributor
- [x] Add youtube embed component folder / file in `/src/components/`
- [x] Add unit tests for the component
- [x] Refactor the About Us page's Youtube video to use this component, essentially replacing `/src/components/about-us/AboutHero.tsx` with the new component.
- [x] Bonus points for writing an end-to-end test to ensure the about us page loads properly, and shows the youtube embed properly.

**Comment by raae** [comment]
YouTube supports oEmbed and a YouTube link can be transformed into html during the build step. Might be helpful to have a look at https://github.com/queen-raae/gatsby-source-youtube-oembed/blob/main/plugin/gatsby-node.js. It transforms an array of YouTube ids into Gatsby nodes.

**Comment by coderbyheart** [comment]
Please provide links to the YouTube videos that should be embedded on the page @wwwwwlwwwww.

**Comment by jtfairbank** [comment]
Thanks for the heads up @raae!  We'll def take a look at that when we implement the gastby-side code that'll use this component.

@coderbyheart I'm going through these issues to get them out of triage, highlighted the YouTube video on the About Us page.

@wwwwwlwwwww I removed the more complex YouTube control options here, I think for the initial implementation we don't need them.  We can use the YouTube embed URL with those parameters set for now.

**Comment by RabeaGleissner** [comment]
I'll pick this one up 📺

**Comment by RabeaGleissner** [comment]
All done!
