### ISSUE TITLE
Add Card Hover Behavior

### ISSUE THREAD

**Issue by JasonFritsche** [distributeaid/distributeaid.org#605]
The Card component should include optional behavior when you hover over it.

This behavior could be changing the cards color, display a tool-tip, or both.

**Comment by coderbyheart** [comment]
Why is this needed?

**Comment by JasonFritsche** [comment]
@coderbyheart This issue was listed as a requirement in #547 but was not implemented in that ticket.

**Comment by coderbyheart** [comment]
Ok, but hover features do not work on mobile and are problematic to make accessible. Therefore we will hold off on this feature until there is a concrete example for the need for a hover feature in the card. /cc @wwwwwlwwwww

**Comment by JasonFritsche** [comment]
Sounds good! Thanks @coderbyheart
