### ISSUE TITLE
Migrate Gatsby from JS to TypeScript

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#618]
Gatsby added build-side support for TypeScript in March '22.  It'd be nice to use TypeScript consistently throughout our codebase.  

### Documentation

  * Gatsby JS > TypeScript - https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#migrating-to-typescript
  * Gatsby Unit Testing TypeScript Setup - https://www.gatsbyjs.com/docs/how-to/testing/unit-testing/#using-typescript
  * CodeSee Map of relevant files to migrate - https://app.codesee.io/maps/public/577b1d60-3306-11ed-af0d-b58e3b81aea3

### Checklist

- [ ] Sign the `/CONTRIBUTORS.md` file if this is your first contribution.
- [ ] Install dependencies.
- [ ] Migrate gatsby build files config files to TypeScript.
- [ ] Migrate other config / top-level files to TypeScript if possible (may depend on TypeScript support from the package that uses them).
- [ ] Document any files that couldn't be migrated (and why) in this issue.
- [ ] Resolve any type issues in the migrated files.
- [ ] Run tests to ensure the site isn't broken.

**Comment by fredericbonnet** [comment]
Hey, happy Hacktoberfest! I'd like to take care of this issue, can you assign it to me?

**Comment by jtfairbank** [comment]
@fredericbonnet there you go!  Don't forget to add your name to `/CONTRIBUTORS.md` file if this is your first time contributing :smile:

**Comment by fredericbonnet** [comment]
PR #736 is ready for review. For some reasons the E2E tests fail on CI even though they pass on my local Gitpod (I haven't touched anything that could explain that)
