### ISSUE TITLE
Use Gatsby's FilesystemRouteAPI for Dynamic Pages

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#623]
Raae suggested this in a discussion https://github.com/distributeaid/distributeaid.org/discussions/593

> Using [the filesystem route api](https://www.gatsbyjs.com/docs/reference/routing/creating-routes/#using-the-file-system-route-api) makes it, in my opinion. easier to navigate the page structure for new developers. Especially since there is already a lot of hard coded pages, and then you can see them side by side.
> 
> For instance inside the regions folder, together with `index.tsx` you could have the routes `{DARegion.name}.tsx` and `{DASubregion.region.name}/{DASubregion.name}.tsx`. Not 100% sure on the syntax, but close enough for this purpose of this feedback zany_face

This makes a lot of sense and allows us to take advantage of page queries that can be hot-reloaded.

CodeSee map of relevant files: https://app.codesee.io/maps/public/005e9e30-3329-11ed-95e1-eb971fd737d9

### Checklist

- [x] Add your name to `/CONTRIBUTORS.md` if this is your first contribution!
- [x] Write end-to-end tests for each page before refactoring.
- [x] Refactor the Region pages to use the filesystem route API instead of `createPage` in `/gatsby-node.js`
- [x] Refactor the Subregion pages to use the filesystem route API instead of `createPage` in `/gatsby-node.js`
- [x] Refactor the Route pages to use the filesystem route API instead of `createPage` in `/gatsby-node.js`
- [x] Ensure the end-to-end tests you wrote are passing.

**Comment by JasonFritsche** [comment]
I can take this one!

**Comment by raae** [comment]
This should be easier when #662 is merged.

The file system route api creates pages in a similar way to what is done in #662, by creating pages from a list of nodes passing the node id as the page context and giving the template the responsibility to query for data.

The remaining issue to be solved before migrating to file system route api is to then to make sure the nodes have a field suitable for usage as slug. I recommend using the markdown filename, and adding that value as a slug field on the node.

You could potentially do something like `src/pages/regions/{Region.parent__(MarkdownRemark).parent__(File)__name}.js` (not verified that it works, but its similar at least), but I prefer setting a slug field on the node and do `src/pages/regions/{Region.slug}.js`.

**Comment by JasonFritsche** [comment]
@raae I'm having a bit of trouble with this one. I was able to get the regions page to show up using a filename similar to ```src/pages/regions/{(MarkdownRemark).parent__(File)__name}.tsx```, i can't recall the exact path because I started exploring alternative options such as using the slug. With regard to doing something like ```{Region.slug}.tsx```, where would the slug come from?

**Comment by raae** [comment]
It would have to be set when creating the node. Ie. when using the function `createNode` to create the region/subregion/route etc.

It's seems to be in place for `DARoute` nodes already: https://github.com/distributeaid/distributeaid.org/blob/70e7bd4d9d1177752b473df595b83ec6280b7675/gatsby/transform-nodes.js#L123

So `{DARoute.slug}.tsx` should work already, and you could replicate setting the slug for all of the nodes being created in that file. Region routes would then be `{DARegion.slug}.tsx}` (forgot about the `DA` in the node types with the example above).

**Comment by JasonFritsche** [comment]
Thank you! Thank you! Thank you! I'm a total noob when it comes to Gatsby. I've read through the Filesystem Route API docs, stackoverflow posts, and have been scouring the internet to try to figure this one out. I've been stumped for bit.

**Comment by jtfairbank** [comment]
Hey @JasonFritsche you can see how we generate slugs for the `DARegion` and `DASubRegion` in the react side.  Look at the regions page, and region / subregion template.  We're using slugify + their names to create the slugs to link between them.

I'd recommend just setting a `slug` field at the node creation stage in `/gatsby/transform-nodes.js` so that the field is accessible to the file-system-route API, and then using that slug instead of rebuilding the links on the react side.  Lmk if you need any help, I'm quite familiar with node creation at this point!

**Comment by JasonFritsche** [comment]
Thanks @jtfairbank! I'll let you know if I need a hand.

**Comment by raae** [comment]
I would recommend using the name of the markdown file as the slug. That way you are sure it's unique. No need to slugify, as the file system route api does that by using [`slugify` by sindresorhus](https://github.com/sindresorhus/slugify).

**Comment by JasonFritsche** [comment]
@jtfairbank I'm going to have to take you up on your offer of help. I've got `pages/regions/{daRegion.name}.tsx` working. I cannot seem to figure out how to generate routes to subregions.

**Comment by raae** [comment]
I could also pair with you on this, but heading for a vacation until Saturday - meaning I could do it Sunday at the earliest.

**Comment by jtfairbank** [comment]
Hey @JasonFritsche, I'm back in the US.  I'll slack you to find a time we can pair?

@raae if we can't figure it out I'll reach out to schedule a session with you!
