### ISSUE TITLE
Extract Totals helper module

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#66]
On [this line](https://github.com/distributeaid/distributeaid.org/blob/saga/src/templates/RegionPage.tsx#L56), we're adding to the page the calculation of a series of shipments' values, as a `totals` object.

It would be good to extract a module that accepts these shipments and returns that values object.

This would allow a consistent way of calculating shipment totals across the codebase.

Previous work done in #26, #65 as a way to resolve #24, see CodeSee recording for latest state:
https://app.codesee.io/shared/c92ab390-3289-11ec-81ae-67b50d769a2b

**Comment by dolatapatryk** [comment]
Hello, can I do this issue? :)

**Comment by hola-soy-milk** [comment]
Sure thing @dolatapatryk, thank you so much for volunteering! I'll assign this to you right away

**Comment by dolatapatryk** [comment]
Done in #67
