### ISSUE TITLE
Style the navigation bar

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#68]
**Previous work**:

Show the logo as content from Contentful.

**Starting point**:
https://app.codesee.io/shared/99dc9ec0-3804-11ec-b5c4-e93c0b8edf5c

Goal:

- [x] Style the navbar so the logo fits fully, making the logo fit dynamically
- [x] Remove the logo title from below the image
- [ ] Right-align the nav links

We want to try and match the style of the proposed design:
https://www.figma.com/file/Ey8xRnstZS4UYmqQwyYZdC/Landing-Page?node-id=208%3A601

**Comment by ZaidMarrie** [comment]
Please assign me this issue if no one else is working on it.

**Comment by hola-soy-milk** [comment]
Go for it, thanks @ZaidMarrie!

**Comment by nguyenhung15913** [comment]
Hi, can I work on this ?

**Comment by ZaidMarrie** [comment]
unassigned myself as I am not familiar with the tech stack used

**Comment by hola-soy-milk** [comment]
Gotcha, thank you for confirming!

All yours if you like, @nguyenhung15913!

**Comment by hola-soy-milk** [comment]
I'll go ahead and take this on for now!
