### ISSUE TITLE
Bug: Some Website Title Sections Reverted to Body Text

### ISSUE THREAD

**Issue by wwwwwlwwwww** [distributeaid/distributeaid.org#690]
### What happened?

There are two sections of the website that used to be in title font but are now in body font.

Before (Home page):
![image](https://user-images.githubusercontent.com/112079473/192528462-814d0159-0883-4822-af56-5bf84eb193cf.png)

After (Home page):
![image](https://user-images.githubusercontent.com/112079473/192528727-d125237e-9e82-48dd-b18b-1e22de2f3ac8.png)

Before (About Us page):
![image](https://user-images.githubusercontent.com/112079473/192528552-2be2d552-ebed-4396-82a9-72f07440b0bf.png)

After (About Us page):
![image](https://user-images.githubusercontent.com/112079473/192528860-4f579edf-5595-45d7-aa18-90ba7feea12c.png)

### Steps to reproduce

1. go to distributeaid.org
2. go to distributeaid.org/about-us

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coderbyheart** [comment]
Caused by 4ca7fe145af3cf3a212dfc70e9f177a585a1761d

**Comment by coderbyheart** [comment]
Thanks for reporting this!
