### ISSUE TITLE
Setup Project Overview On Notion

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#7]

**Comment by iulspop** [comment]
Hi,

The [link to the project overview](https://www.notion.so/c85002a23d94423bb79f4c64802c4c47) in the README under "Key Documents" leads to a restricted page:
![image](https://user-images.githubusercontent.com/53665722/127784183-3ba0c0da-6eb2-497d-913a-6bea0662b1d0.png)

You can fix that by making the notion document public on the web.

**Comment by jtfairbank** [comment]
Decided to keep notion as an internal tool, there's a lot more documentation on the project itself now (readme, issues, etc).
