### ISSUE TITLE
[Tailwind] The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#715]
Update the configuration to get rid of this warning when the dev server is started.

```
warn warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
warn warn - Change `darkMode` to `media` or remove it entirely.
warn warn - https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
```

**Comment by dorian-edwards** [comment]
Hey @coderbyheart, can I work on this?

**Comment by coderbyheart** [comment]
Sure!

**Comment by dorian-edwards** [comment]
Do we want darkMode to be media or class? If we want media should I set it explicitly or remove it altogether since media is the default?

**Comment by coderbyheart** [comment]
Good questions, right now we do not have support for dark mode, and proper support would take some extra work, so it's O.K. to disable it for now.
