### ISSUE TITLE
[Codesee] Module not found: Can't resolve 'vue'

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#716]
Figure out what causes this error when starting the dev server and fix it.

```
warn ./node_modules/@codesee/tracker/build/codesee.web.hosted.js
Module not found: Can't resolve 'vue' in '/home/m/da/distributeaid.org/node_modules/@codesee/tracker/build'
```

This is a bug in `@codesee/tracker`, and should be fixed upstream.

**Comment by dorian-edwards** [comment]
Can I have a go at this one too?

**Comment by coderbyheart** [comment]
Sure!

**Comment by jtfairbank** [comment]
Marking this one as "wontfix" and closing it.  It's a harmless error that would be difficult to remove, see the discussion around here: https://github.com/distributeaid/distributeaid.org/pull/724#issuecomment-1265493901
