### ISSUE TITLE
Instructions to open gitpod from VS Code desktop unclear

### ISSUE THREAD

**Issue by EmReedCodes** [distributeaid/distributeaid.org#725]
### What happened?

![image](https://user-images.githubusercontent.com/96320126/193652015-90c43e85-cfc8-4915-b030-062b55520965.png)
Choosing Linux fixed the error but when asked it seemed like you should your operating system so many will click on Windows.
There should be some directions in the documentation for those starting out. 
I would be happy to take on this issue and add the fix.

### Steps to reproduce

1. Open GitPod and choose VS Code desktop
2.  Choose Windows for desktop
3.  Follow steps from VS Code after entering password the error appears.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hola-soy-milk** [comment]
Feel free, thanks @EmReedCodes !
