### ISSUE TITLE
Fix TypeScript errors

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#756]
Right now we have [27 errors in 14 files](https://github.com/distributeaid/distributeaid.org/actions/runs/3212078953/jobs/5250676583#step:8:1).

After [having fully switched to TypeScript](https://github.com/distributeaid/distributeaid.org/pull/736), we should aim to have 0 errors reported for our TypeScript code.

Pick any error you like, fix it in a PR and reference this issue in your PR. After merging, I will update [the PR that adds the check](https://github.com/distributeaid/distributeaid.org/pull/755).

**Comment by alissonmdo** [comment]
Hi @coderbyheart! I created a PR that solves the type errors when importing svg files. It solves almost half the errors. Will try to check the rest when I have some time.

ps: I'm super happy in helping a project that help people in need!

**Comment by Huluvu424242** [comment]
Hi @alissonmdo! I have try it to solve too in [PR 758](https://github.com/distributeaid/distributeaid.org/pull/758). I have used an alternate solution or workaround? Please cherry pick if parts are usefull.

**Comment by coderbyheart** [comment]
Remaining errors fix in #755
