### ISSUE TITLE
Gitpod failing to run e2e tests

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#763]
### What happened?

I ran `yarn test:e2e` and the tests failed.

What's missing is to install the necessary dependencies:

    npx playwright install-deps

We'd need to add a config to our `.gitpod.yml` [configuration file](https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml).

### Steps to reproduce

1. Load the [Gitpod container](https://gitpod.io/#https://github.com/distributeaid/distributeaid.org)
2. Run `yarn test:e2e`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RabeaGleissner** [comment]
I've never worked with Gitpod but it looks very cool. Will have a look at this issue!
