### ISSUE TITLE
Refactor Route Pages

### ISSUE THREAD

**Issue by jtfairbank** [distributeaid/distributeaid.org#777]
### Description

It'd be helpful to refactor portions of the route page into their own components, similar to the home page or about-us page.  There's some existing routes components in `/src/components/routes` but those have more to do with structuring the content than separating it.  It'd be good to have separate components for each section of content, which still use the existing components to structure themselves.

[CodeSee Map of relevant files.](https://app.codesee.io/maps/public/ea3cee90-4f16-11ed-ad82-abc14cafa441)

This should pave the way for:

1. Refactoring the route page's legacy styles to use tailwind classes (see #772)
2. Pulling more of the content out to be controlled by Forestry (our CMS) instead of hard-coded onto the page.
3. Reusable chunks of content that can be applied elsewhere (such as an FAQ).

### Checklist

- [x] Add your name to `/CONTRIBUTORS.md` if this is your first contribution!
- [x] Delivery Section => Component
- [x] Reservations Section => Component
- [x] Frontline Section => Component
- [x] Staging Hubs Section => Component
- [x] Costs Section => Component
- [x] About Pallets Section => Component

### Front end feature screenshots

This refactoring shouldn't change how the content appears on the website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RabeaGleissner** [comment]
I'll start with the Delivery section!

**Comment by linds0202** [comment]
I would like to work on refactoring the 'Costs' and 'About Pallets' components

**Comment by RabeaGleissner** [comment]
Hoping to raise a PR for Frontline and Staging Hubs sections soon!

**Comment by jtfairbank** [comment]
Hey @RabeaGleissner @linds0202 thanks so much for tackling this one!  If you want to continue with refactoring-related work, I'd suggest looking at #772?  If figure there's enough there that y'all can split it up with @20RitikSingh?
