### ISSUE TITLE
Overview page and breakout page does not show all three donation options

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#783]
## Resolution

![Image](https://user-images.githubusercontent.com/188915/196795665-259437f1-d648-411a-9d9d-df28d2a5ad1e.png)

## Question

We have three donation options, only two are shown [in the design](https://drive.google.com/file/d/1aHIAWor62ieyU1b_gDOXC6eba0Ianmql/view?usp=sharing); and we do not use Wise.

Is this intentional?

## Overview page

![Image](https://user-images.githubusercontent.com/188915/196539513-dbf85d77-ac56-4561-9141-f115b287d7b5.png)

## Breakout page

![Image](https://user-images.githubusercontent.com/188915/196540675-ddc922bc-a336-4bd2-b278-a209c1ea0769.png)

**Comment by jtfairbank** [comment]
@coderbyheart we use Wise for our international banking, that's what the bank information points to on the current donate page.  Might just be a case of using the Wise logo on one screen and the bank info symbol on another, even tho they point to the same thing?  Will probably need Florence or Ellie to confirm tho, and answer this question if that's not the case.

**Comment by coderbyheart** [comment]
New design now has Bank Transfer.

![Image](https://user-images.githubusercontent.com/188915/196795665-259437f1-d648-411a-9d9d-df28d2a5ad1e.png)

Regarding Wise on the Donate page: I'd rather that we mention Bank Transfer  instead of Wise because Wise is not universally known. I'll see if can find a good solution.
