### ISSUE TITLE
what should be the URL of the Giving Tuesday 2022 page?

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#786]
Answer: https://distributeaid.org/donate

**Comment by coderbyheart** [comment]
My suggestion would be to replace https://distributeaid.org/donate. In that case: where should we mention Patreon?

**Comment by jtfairbank** [comment]
@coderbyheart agreed, we want to replace our donation page.  I think we're transitioning away from Patreon so it's fine if it's not listed.  Folks can setup recurring donations via Open Collective!
