### ISSUE TITLE
what should happen to the existing donation page?

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#787]
https://distributeaid.org/donate

**Comment by jtfairbank** [comment]
@coderbyheart we can replace it.  I believe most of its content, except Patreon, will be included on the "Giving Tuesday" page.  Even tho the new donate page is being set up as part of our fundraising push around Giving Tuesday, we'll continue to maintain it by updating totals and changing out projects on a regular basis.

**Comment by coderbyheart** [comment]
The existing donating page will be replaced will replaced with the new one
