### ISSUE TITLE
Use numbers from `<ol>` HTML element rather than hard coded numbers

### ISSUE THREAD

**Issue by RabeaGleissner** [distributeaid/distributeaid.org#807]
### Description

In the Reservations section on the Routes pages, there are some step by step instructions with headings starting with numbers. For example here: https://github.com/distributeaid/distributeaid.org/blob/8b155f31e5b4cf68536b8deef5ab78a2906d6d1f/src/components/routes/Reservations.tsx#L64

These numbers are currently hard-coded as part of the content but it would be more idiomatic to use the numbers that come from the `<ol>` component (which are currently hidden). 

### Front end feature screenshots

Example of the step by step instructions that I mean:
https://distributeaid.org/routes/uk-to-france/
<img width="712" alt="image" src="https://user-images.githubusercontent.com/8995723/198087144-c90e7ea4-1d65-4c87-8e9d-9328a1df290e.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aksa12** [comment]
Hey, I would like to work on this issue

**Comment by coderbyheart** [comment]
Great, go ahead @Aksa12!
