### ISSUE TITLE
Add E2E test for Routes pages

### ISSUE THREAD

**Issue by RabeaGleissner** [distributeaid/distributeaid.org#815]
### Description

Please see the second point in this comment for more info: https://github.com/distributeaid/distributeaid.org/pull/791#pullrequestreview-1152337107 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Myrfion** [comment]
Hi, I will try to approach this one

**Comment by coderbyheart** [comment]
Great, @Myrfion, I've assigned the issue to you!

**Comment by jtfairbank** [comment]
Closed by #818
