### ISSUE TITLE
"Donate to undefined" in page title

### ISSUE THREAD

**Issue by coderbyheart** [distributeaid/distributeaid.org#866]
### What happened?

![image](https://user-images.githubusercontent.com/188915/203666243-f21748d2-3611-4150-8a4c-0da1eb8135a1.png)

### Steps to reproduce

Go to https://distributeaid.org/donate/tech-for-good/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonFritsche** [comment]
@coderbyheart  I'll take a look at this one.

**Comment by JasonFritsche** [comment]
[CodeSee Map for this issue](https://app.codesee.io/maps/fd1e0ba0-6de0-11ed-a148-c1cb230d3d63)

**Comment by coderbyheart** [comment]
Fixed via #869
