### ISSUE TITLE
"More info" buttons in the donate page show an incorrect icon

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#886]
### What happened?

When visiting the [donate page](https://distributeaid.org/donate/), they look like this:
![Screenshot of the website showing the "More Info" button having a question mark](https://user-images.githubusercontent.com/656318/206542662-956d39d7-3cad-47b8-abdb-173dadf67b3a.png)

This should be an HTML arrow

This is likely being caused in the [arrow displaying function](https://github.com/distributeaid/distributeaid.org/blob/saga/src/components/fundraiser/FundraiserCard.tsx#L115)

### Steps to reproduce

Reproduced on Chrome 107.0.5304.110 on macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kd-Here** [comment]
Hey @hola-soy-milk You are doing a really good help by creating donation system.
I would loved to help you with this issue but can't produce this condition don't have macos!
Is there any other think where I can help you

**Comment by ArshErgon** [comment]
Hey @hola-soy-milk  will this arrow will work? '➤' its code is &#x27A4;

**Comment by fedechaves** [comment]
hey @jtfairbank, you should check this issue, this is an update of Ramon's screenshot:
![image](https://user-images.githubusercontent.com/90200540/212790051-a85d77d6-58bb-418e-878e-b021d48772dc.png)

**Comment by jtfairbank** [comment]
@fedechaves which OS and browser were you using?  It might work in some but not others.

For me: Elementary OS, works in Firefox 104 and Chrome 102

**Comment by fedechaves** [comment]
@jtfairbank  I was using Windows 10 and works fine in Brave and Chrome

**Comment by hola-soy-milk** [comment]
Hey all! Thanks for contributing to this discussion.

I just checked on Chrome on macOS, still looks like this:
![image](https://user-images.githubusercontent.com/656318/212954790-c9447ac8-92d7-4ef7-b7b0-caa243620ae7.png)
