### ISSUE TITLE
Add PayPal embed to donate page

### ISSUE THREAD

**Issue by wwwwwlwwwww** [distributeaid/distributeaid.org#974]
### Description

Add PayPal embedded donate portal to Donate page.

 * Waiting on hearing back for the embed code
 * Waiting on hearing back about specific placement desired/front end screenshot

### Front end feature screenshots

TBD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtfairbank** [comment]
@wwwwwlwwwww Paypal has a number of issues that make me concerned about using it prominently.  Namely, their conversion rates / fees + the fact that PayPal can / will lock up funds indefinitely if you happen to get unlucky and their team flags the account for whatever reason.

I'd prefer to embed something that we're more in control of, such as Donor Box hooked up to a Stripe account that we setup.  https://donorbox.org/
